version: '3.8'

services:
  cassandra-node2:
    image: cassandra:4.1
    container_name: cassandra-node2
    ports:
      - "9042:9042"      # Puerto CQL nativo
      - "7000:7000"      # Puerto de comunicación/gossip inter-nodo (Crítico para Tailscale)
      - "7199:7199"      # Puerto JMX para nodetool status/ring
    environment:
      - CASSANDRA_CLUSTER_NAME=SEMAPA_CLUSTER
      - CASSANDRA_SEEDS=100.71.121.5                 # IP Tailscale de PC 1 (Seed/Principal)
      - CASSANDRA_BROADCAST_ADDRESS=100.114.64.8     # Anuncia esta IP de Tailscale (PC Secundaria)
      - CASSANDRA_RPC_ADDRESS=0.0.0.0                # Escucha en todas las interfaces para conexiones
      - CASSANDRA_BROADCAST_RPC_ADDRESS=100.114.64.8 # Anuncia esta IP para que los clientes se conecten
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_NUM_TOKENS=16
    volumes:
      - cassandra_node2_data:/var/lib/cassandra

volumes:
  cassandra_node2_data:
